### ISSUE TITLE
[witherspoon DD 2.1] lsmcode returns Failed to get System Firmware information

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/lsvpd#1]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=164134 </cde:info>

command to run: lsmcode
result: Failed to get System Firmware information

logs show:

Jan 31 04:08:46 ltc-wspoon5 ipmievd: System Event sensor - Undetermined system hardware failure

[root@ltc-wspoon5 ibm,firmware-versions]# uname -r
4.15.0-2.rc9.dev.git03552b2.el7.centos.ppc64le
[root@ltc-wspoon5 ibm,firmware-versions]# rpm -qa | grep vpd
lsvpd-1.7.8-3.dev.gitc36b20b.el7.centos.ppc64le
libvpd-2.2.5-8.dev.git7d959c5.el7.centos.ppc64le

**Comment by bssrikanth** [comment]
@hegdevasant have raised issue.

**Comment by bssrikanth** [comment]
[root@ltc-wspoon5 ibm,firmware-versions]# lsprop
occ              "39d5490"
skiboot          "v5.9.8"
buildroot        "2017.08-8-g5e23247"
capp-ucode       "p9-dd2-v2"
petitboot        "v1.6.3-p9911320"
sbe              "b6b7bb7"
phandle          0000016c (364)
hostboot-binaries
		 "159f2e8"
machine-xml      "592a6dd"
hostboot         "7050d0a"
name             "ibm,firmware-versions"
linux            "4.13.16-openpower1-p98dd271"

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2018-01-31 23:30:53 EDT-------
I've pushed couple of patches to lsvpd devel branch. That should fix this issue. Please verify.

-Vasant

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2018-02-01 05:59:17 EDT-------
Thank you.

atleast it's not there in today devel.. will verify with build tomorrow.

**Comment by cdeadmin** [comment]
------- Comment From bssrikanth@in.ibm.com 2018-02-03 03:56:07 EDT-------
[root@ltc-wspoon5 ~]# rpm -qa | grep vpd
libvpd-2.2.5-8.dev.git7d959c5.el7.centos.ppc64le
lsvpd-1.7.8-4.dev.git63c0dfc.el7.centos.ppc64le

[root@ltc-wspoon5 ~]# lsmcode
Version of System Firmware : 
 Product Name          : OpenPOWER Firmware
 Product Extra         : 	occ-39d5490
 Product Extra         : 	skiboot-v5.9.8
 Product Extra         : 	buildroot-2017.08-8-g5e23247
 Product Extra         : 	capp-ucode-p9-dd2-v2
 Product Extra         : 	petitboot-v1.6.3-p9911320
 Product Extra         : 	sbe-b6b7bb7
 Product Extra         : 	hostboot-binaries-159f2e8
 Product Extra         : 	machine-xml-592a6dd
 Product Extra         : 	hostboot-7050d0a
 Product Extra         : 	linux-4.13.16-openpower1-p98dd271

Closing as per above test. Thank you.
